import { useQueries } from '@tanstack/react-query';
import { Activity, ArrowLeft, ArrowUpRight, Clock3, ExternalLink, Globe2, ShieldCheck } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { StatusPill, getState } from '../components/StatusPill';
import { monitorService } from '../services/monitors';
import { errorMessage } from '../lib/api';

const formatDate = (value: string) => new Date(value).toLocaleString([], { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
export function MonitorPage() {
  const { id = '' } = useParams();
  const [monitor, checks, incidents] = useQueries({ queries: [
    { queryKey: ['monitors', id], queryFn: () => monitorService.get(id), enabled: !!id, refetchInterval: 30_000 },
    { queryKey: ['monitors', id, 'checks'], queryFn: () => monitorService.checks(id), enabled: !!id },
    { queryKey: ['monitors', id, 'incidents'], queryFn: () => monitorService.incidents(id), enabled: !!id },
  ] });
  if (monitor.isPending) return <div className="details-loading"><div className="loading-ring" />Loading monitor…</div>;
  if (monitor.isError || !monitor.data) return <div className="api-alert"><Activity size={18} /><div><strong>Monitor not available</strong><span>{monitor.isError ? errorMessage(monitor.error) : 'This monitor may have been removed.'}</span></div><Link to="/" className="text-button">Back to overview <ArrowLeft size={14} /></Link></div>;
  const item = monitor.data;
  const points = [...(checks.data ?? [])].reverse().map((check) => ({ ...check, label: new Date(check.checkedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }), latency: check.responseTimeMs ?? 0 }));
  return <>
    <Link to="/" className="back-link"><ArrowLeft size={15} />Back to overview</Link>
    <div className="detail-title-row"><div className="detail-title-icon"><Globe2 size={21} /></div><div className="detail-title-copy"><h1>{item.name}</h1><a href={item.url} target="_blank" rel="noreferrer">{item.url}<ExternalLink size={13} /></a></div><StatusPill state={getState(item)} /><Link to={`/status/${item.slug}`} className="button button-secondary share-status">Public status page <ArrowUpRight size={14} /></Link></div>
    <div className="detail-stat-grid"><div className="detail-stat-card"><span>Current status</span><strong className="detail-status"><i className={`state-dot state-dot-${getState(item)}`} />{getState(item) === 'operational' ? 'Operational' : getState(item) === 'down' ? 'Service down' : getState(item) === 'paused' ? 'Paused' : getState(item) === 'degraded' ? 'Degraded' : 'Waiting'}</strong><small>Last checked {item.stats.latestCheck ? formatDate(item.stats.latestCheck.checkedAt) : '—'}</small></div><div className="detail-stat-card"><span>Uptime · 24 hours</span><strong>{item.stats.uptime24h == null ? '—' : `${item.stats.uptime24h.toFixed(2)}%`}</strong><small>{item.stats.checks24h} checks recorded</small></div><div className="detail-stat-card"><span>Uptime · 7 days</span><strong>{item.stats.uptime7d == null ? '—' : `${item.stats.uptime7d.toFixed(2)}%`}</strong><small>{item.stats.checks7d} checks recorded</small></div><div className="detail-stat-card"><span>Average response</span><strong>{item.stats.averageResponseTimeMs == null ? '—' : `${Math.round(item.stats.averageResponseTimeMs)} ms`}</strong><small>Past 7 days</small></div></div>
    <div className="detail-panel"><div className="panel-heading"><div><h2>Response time</h2><p>Each point is one of the latest 100 HTTP checks.</p></div><span className="chart-legend"><i />Response time</span></div>{points.length > 1 ? <div className="detail-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={points} margin={{ top: 12, right: 8, bottom: 0, left: 0 }}><defs><linearGradient id="latencyGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#6875e8" stopOpacity={0.22} /><stop offset="100%" stopColor="#6875e8" stopOpacity={0.02} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#edf0f5" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: '#989daa', fontSize: 11 }} minTickGap={45} /><YAxis tickLine={false} axisLine={false} tick={{ fill: '#989daa', fontSize: 11 }} width={42} tickFormatter={(value) => `${value}ms`} /><Tooltip contentStyle={{ border: '1px solid #e8eaf0', borderRadius: 10, fontSize: 12 }} formatter={(value) => [`${value} ms`, 'Response']} /><Area type="monotone" dataKey="latency" stroke="#6875e8" strokeWidth={2.2} fill="url(#latencyGradient)" isAnimationActive={false} /></AreaChart></ResponsiveContainer></div> : <div className="chart-placeholder"><div><Activity size={20} /><span>Response time chart appears after a few checks.</span></div></div>}</div>
    <div className="detail-lower-grid"><section className="detail-panel"><div className="panel-heading"><div><h2>Recent checks</h2><p>Latest endpoint responses</p></div><span className="panel-count">{checks.data?.length ?? 0}</span></div><div className="check-list">{checks.isPending ? <p className="list-placeholder">Loading checks…</p> : checks.data?.length ? checks.data.slice(0, 8).map((check) => <div className="check-row" key={check.id}><span className={`check-dot ${check.isOnline ? 'online' : 'offline'}`} /><div><strong>{check.isOnline ? 'Successful response' : check.errorMessage || 'Request failed'}</strong><span>{formatDate(check.checkedAt)}</span></div><b>{check.statusCode ? `HTTP ${check.statusCode}` : '—'}</b><em>{check.responseTimeMs == null ? '—' : `${check.responseTimeMs} ms`}</em></div>) : <p className="list-placeholder">No checks yet. The scheduler will run shortly.</p>}</div></section><section className="detail-panel"><div className="panel-heading"><div><h2>Incident history</h2><p>Service interruptions and recovery</p></div><span className="panel-count">{incidents.data?.length ?? 0}</span></div><div className="incident-list">{incidents.isPending ? <p className="list-placeholder">Loading incidents…</p> : incidents.data?.length ? incidents.data.slice(0, 8).map((incident) => <div className="incident-row" key={incident.id}><span className={`incident-marker ${incident.status.toLowerCase()}`} /><div><strong>{incident.status === 'OPEN' ? 'Ongoing incident' : 'Service recovered'}</strong><span>{incident.initialError || 'Endpoint unavailable'}</span><small>{formatDate(incident.startedAt)}{incident.resolvedAt ? ` · Resolved ${formatDate(incident.resolvedAt)}` : ''}</small></div></div>) : <div className="incidents-empty"><ShieldCheck size={23} /><strong>All clear</strong><span>No incidents have been recorded.</span></div>}</div></section></div>
    <div className="detail-footer"><span><Clock3 size={14} />Checks every 60 seconds</span><span>Public page <Link to={`/status/${item.slug}`}>pulseboard.app/status/{item.slug} <ArrowUpRight size={12} /></Link></span></div>
  </>;
}
