import { useQuery } from '@tanstack/react-query';
import { ArrowLeft, ArrowUpRight, CircleCheck, CircleDashed, Clock3, Globe2, RadioTower, ShieldCheck } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { monitorService } from '../services/monitors';
import { errorMessage } from '../lib/api';
import { getState, StatusPill } from '../components/StatusPill';
import { LatencyChart } from '../components/LatencyChart';

export function PublicStatusPage() {
  const { slug = '' } = useParams();
  const query = useQuery({ queryKey: ['public-status', slug], queryFn: () => monitorService.status(slug), refetchInterval: 30_000 });
  if (query.isPending) return <div className="public-loading"><div className="loading-ring" />Loading service status…</div>;
  if (query.isError || !query.data) return <div className="public-error"><div className="brand-mark"><RadioTower size={19} /></div><h1>Status page unavailable</h1><p>{query.isError ? errorMessage(query.error) : 'This public status page could not be found.'}</p><Link to="/" className="text-button"><ArrowLeft size={14} />Return to PulseBoard</Link></div>;
  const { monitor, stats, incidents, checks } = query.data;
  const state = getState({ enabled: monitor.enabled, stats });
  const history = checks.map((check) => ({ responseTimeMs: check.responseTimeMs, isOnline: check.isOnline, checkedAt: check.checkedAt }));
  const healthy = state === 'operational' || state === 'degraded';
  return <main className="public-page"><div className="public-header"><Link className="public-brand" to="/"><span className="brand-mark"><RadioTower size={18} /></span>pulseboard</Link><span className="public-view-label"><span /> LIVE STATUS</span></div><section className="public-content"><div className="public-service-label"><Globe2 size={15} /><span>PUBLIC SERVICE STATUS</span></div><div className="public-title-row"><div><h1>{monitor.name}</h1><a href={monitor.url} target="_blank" rel="noreferrer">{monitor.url.replace(/^https?:\/\//, '').replace(/\/$/, '')} <ArrowUpRight size={13} /></a></div><StatusPill state={state} /></div>
    <div className={`public-banner ${healthy ? 'all-operational' : state === 'paused' ? 'service-paused' : 'service-disrupted'}`}>{healthy ? <CircleCheck size={19} /> : state === 'paused' ? <CircleDashed size={19} /> : <CircleDashed size={19} />}<div><strong>{healthy ? 'All systems operational' : state === 'paused' ? 'Monitoring is paused' : state === 'pending' ? 'Waiting for the first check' : 'Service disruption detected'}</strong><span>{stats.latestCheck ? `Last checked ${new Date(stats.latestCheck.checkedAt).toLocaleString()}` : 'PulseBoard checks this endpoint every 60 seconds.'}</span></div><span className="live-refresh"><i />Updates automatically</span></div>
    <section className="public-stat-grid"><div><span>Uptime · 24 hours</span><strong>{stats.uptime24h == null ? '—' : `${stats.uptime24h.toFixed(2)}%`}</strong><small>Rolling window</small></div><div><span>Uptime · 7 days</span><strong>{stats.uptime7d == null ? '—' : `${stats.uptime7d.toFixed(2)}%`}</strong><small>Rolling window</small></div><div><span>Avg. response</span><strong>{stats.averageResponseTimeMs == null ? '—' : `${Math.round(stats.averageResponseTimeMs)} ms`}</strong><small>Past 7 days</small></div><div><span>Last checked</span><strong className="public-last-check">{stats.latestCheck ? new Date(stats.latestCheck.checkedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '—'}</strong><small><Clock3 size={12} /> Every minute</small></div></section>
    <section className="public-panel"><div className="panel-heading"><div><h2>Response time</h2><p>Endpoint latency over the last 24 hours.</p></div><span className="chart-legend"><i />Latency</span></div><div className="public-chart"><LatencyChart data={history} id={`public-${monitor.id}`} height={150} /></div></section>
    <section className="public-panel public-incident-panel"><div className="panel-heading"><div><h2>Recent incidents</h2><p>Latest service events and recoveries.</p></div><span className="panel-count">{incidents.length}</span></div>{incidents.length ? <div className="public-incident-list">{incidents.slice(0, 5).map((incident) => <div key={incident.id} className="public-incident"><span className={`incident-marker ${incident.status.toLowerCase()}`} /><div><strong>{incident.status === 'OPEN' ? 'Ongoing incident' : 'Resolved incident'}</strong><span>{incident.initialError || 'Service unavailable'}</span><small>{new Date(incident.startedAt).toLocaleString()}{incident.resolvedAt ? ` · Recovered ${new Date(incident.resolvedAt).toLocaleString()}` : ''}</small></div></div>)}</div> : <div className="public-clear"><ShieldCheck size={19} /><span>No incidents reported in this service’s history.</span></div>}</section>
    <div className="public-foot"><span><ShieldCheck size={14} />Status information provided by PulseBoard</span><Link to="/">Monitor your own service <ArrowUpRight size={12} /></Link></div></section><footer className="public-footer">Reliable updates, one check at a time <span>·</span> PulseBoard © 2026</footer></main>;
}
